import { PDFDocument } from 'pdf-lib';
import sharp from 'sharp';
import { SchemeChunk } from '@models/SchemeChunk.model.js';

interface CitationResult {
  chunkId: string;
  schemeId: string;
  pageNumber: number;
  text: string;
  score: number;
}

interface ProofCardData {
  schemeName: string;
  eligible: boolean;
  citationText: string;
  page: number;
  confidence: number;
}

export const citationService = {
  formatCitation(chunk: { chunkText: { en: string }; pageNumber: number; schemeName: { en: string } }): string {
    return `[${chunk.schemeName.en}, Page ${chunk.pageNumber}] "${chunk.chunkText.en.substring(0, 200)}..."`;
  },

  extractPageAndParagraph(chunk: { chunkText: { en: string }; pageNumber: number }): { page: number; paragraph: string } {
    return {
      page: chunk.pageNumber,
      paragraph: chunk.chunkText.en.substring(0, 500),
    };
  },

  async getCitationsForScheme(schemeId: string, query: string): Promise<CitationResult[]> {
    const chunks = await SchemeChunk.find({ schemeId, isEligibilitySection: true }).limit(5).lean();
    return chunks.map(chunk => ({
      chunkId: chunk._id.toString(),
      schemeId: chunk.schemeId,
      pageNumber: chunk.pageNumber,
      text: chunk.chunkText.en,
      score: 1.0,
    }));
  },

  async extractPageAsImage(pdfBuffer: Buffer, pageNumber: number): Promise<Buffer> {
    const pdfDoc = await PDFDocument.load(pdfBuffer);
    const totalPages = pdfDoc.getPageCount();
    const targetPage = Math.min(pageNumber, totalPages - 1);

    const singleDoc = await PDFDocument.create();
    const [copied] = await singleDoc.copyPages(pdfDoc, [targetPage]);
    singleDoc.addPage(copied);

    return Buffer.from(await singleDoc.save());
  },

  async generateProofCard(data: ProofCardData): Promise<Buffer> {
    const width = 700;
    const height = 450;
    const truncatedText = data.citationText.length > 180
      ? data.citationText.substring(0, 180) + '...'
      : data.citationText;

    const escapedText = truncatedText.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const escapedSchemeName = data.schemeName.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

    const badgeColor = data.eligible ? '#16a34a' : '#dc2626';
    const badgeText = data.eligible ? '✓ ELIGIBLE' : '✗ NOT ELIGIBLE';
    const confidencePct = Math.round(data.confidence * 100);

    const svg = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="bg" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" style="stop-color:#f0fdf4;stop-opacity:1"/>
          <stop offset="100%" style="stop-color:#dcfce7;stop-opacity:1"/>
        </linearGradient>
      </defs>
      <rect width="${width}" height="${height}" fill="url(#bg)" rx="12"/>
      <rect x="1" y="1" width="${width - 2}" height="${height - 2}" fill="none" stroke="#16a34a" stroke-width="2" rx="12"/>
      <rect x="0" y="0" width="${width}" height="60" fill="#15803d" rx="12"/>
      <rect x="0" y="48" width="${width}" height="12" fill="#15803d"/>
      <text x="24" y="38" font-family="Arial,sans-serif" font-size="20" font-weight="bold" fill="white">Niti-Setu AjraSakha — Eligibility Proof</text>
      <text x="24" y="88" font-family="Arial,sans-serif" font-size="16" font-weight="600" fill="#166534">${escapedSchemeName}</text>
      <rect x="24" y="104" width="${width - 48}" height="1" fill="#bbf7d0"/>
      <text x="24" y="135" font-family="Arial,sans-serif" font-size="13" fill="#374151">Document Evidence (Page ${data.page}):</text>
      <rect x="24" y="148" width="${width - 48}" height="90" fill="white" rx="6" stroke="#d1fae5" stroke-width="1"/>
      <foreignObject x="32" y="154" width="${width - 64}" height="78">
        <body xmlns="http://www.w3.org/1999/xhtml">
          <p style="font-family:Arial,sans-serif;font-size:12px;color:#374151;margin:0;line-height:1.5">${escapedText}</p>
        </body>
      </foreignObject>
      <rect x="24" y="258" width="160" height="44" fill="${badgeColor}" rx="8"/>
      <text x="104" y="285" font-family="Arial,sans-serif" font-size="15" font-weight="bold" fill="white" text-anchor="middle">${badgeText}</text>
      <text x="220" y="275" font-family="Arial,sans-serif" font-size="13" fill="#374151">Confidence:</text>
      <rect x="310" y="262" width="200" height="16" fill="#e5e7eb" rx="8"/>
      <rect x="310" y="262" width="${Math.round(200 * data.confidence)}" height="16" fill="${badgeColor}" rx="8"/>
      <text x="520" y="275" font-family="Arial,sans-serif" font-size="13" fill="#374151">${confidencePct}%</text>
      <text x="24" y="350" font-family="Arial,sans-serif" font-size="11" fill="#6b7280">Generated by Niti-Setu AjraSakha • ${new Date().toLocaleDateString('en-IN')} • AI-powered Scheme Eligibility System</text>
    </svg>`;

    return sharp(Buffer.from(svg)).png({ quality: 95 }).toBuffer();
  },
};